export { SentiSense } from "./client.js";
export { SentiSense as default } from "./client.js";

export {
  SentiSenseError,
  AuthenticationError,
  NotFoundError,
  RateLimitError,
  APIError,
} from "./errors.js";

export type {
  SentiSenseOptions,
  Insight,
  InsightPreviewResponse,
  LockedInsight,
  GetInsightsOptions,
  InsiderActivitySummary,
  InsiderActivityResponse,
  InsiderTrade,
  ClusterBuy,
  GetInsiderOptions,
  CongressTrade,
  PoliticianSummary,
  PoliticianDetail,
  GetPoliticiansOptions,
  PreviewResponse,
  StockPrice,
  StockDetail,
  StockImage,
  StockProfile,
  StockEntity,
  ChartData,
  ChartDataPoint,
  MarketStatus,
  Fundamentals,
  FundamentalsPeriod,
  ShortInterest,
  FloatInfo,
  ShortVolume,
  AISummary,
  MetricsBreakdown,
  Document,
  DocumentSource,
  SentimentEntry,
  Story,
  StoryCluster,
  Quarter,
  InstitutionalFlow,
  InstitutionalFlowsResponse,
  Holder,
  MetricType,
  MetricsOptions,
  MetricDistributionOptions,
  ServingMetric,
  MetricDistribution,
  MentionData,
  MentionCount,
  SentimentData,
  MarketMood,
  MarketSummary,
  KBEntity,
} from "./types.js";

export { VERSION } from "./version.js";
