export { SentiSense } from "./client.js";
export { SentiSense as default } from "./client.js";

export type {
  AnalystConsensus,
  AnalystAction,
  AnalystEstimate,
  AnalystEarningsSurprise,
  AnalystEstimatesResponse,
  GetAnalystActionsOptions,
  GetAnalystMarketActivityOptions,
} from "./resources/analyst.js";

export type {
  GetStockInsightsRangeOptions,
  GetLatestInsightsOptions,
  GetUserInsightsOptions,
} from "./resources/insights.js";

// ETF aggregate types
export type {
  EtfInfo,
  EtfHolding,
  EtfHoldings,
  EtfAggregateCoverage,
  WeightedConsensus,
  EtfAnalystContributor,
  EtfAnalystAggregate,
  WeightedNetFlow,
  EtfInsiderContributor,
  EtfInsiderAggregate,
  EtfSentimentReading,
  EtfSentimentAggregate,
  GetEtfInsiderAggregateOptions,
} from "./resources/etfs.js";

// KPI types
export type {
  KpiDataPoint,
  KpiSeries,
  CompanyKpisData,
  KpiCoverageEntry,
  KpiCoverageResponse,
  KpiTypeEntry,
} from "./types.js";

export {
  SentiSenseError,
  AuthenticationError,
  NotFoundError,
  RateLimitError,
  APIError,
} from "./errors.js";

export type {
  SentiSenseOptions,
  Insight,
  InsightPreviewResponse,
  LockedInsight,
  GetInsightsOptions,
  InsiderActivitySummary,
  InsiderActivityResponse,
  InsiderTrade,
  ClusterBuy,
  GetInsiderOptions,
  CongressTrade,
  PoliticianSummary,
  PoliticianDetail,
  GetPoliticiansOptions,
  PreviewResponse,
  StockPrice,
  StockQuote,
  StockDetail,
  SimilarStock,
  StockImage,
  StockProfile,
  StockEntity,
  ChartData,
  ChartDataPoint,
  MarketStatus,
  Fundamentals,
  FundamentalsPeriod,
  ShortInterest,
  FloatInfo,
  ShortVolume,
  AISummary,
  MetricsBreakdown,
  Document,
  DocumentSource,
  SentimentEntry,
  Story,
  StoryCluster,
  Quarter,
  InstitutionalFlow,
  InstitutionalFlowsResponse,
  Holder,
  InstitutionSummary,
  InstitutionList,
  InstitutionListResponse,
  ListInstitutionsOptions,
  MetricType,
  MetricsOptions,
  MetricDistributionOptions,
  ServingMetric,
  MetricDistribution,
  MentionData,
  MentionCount,
  SentimentData,
  MarketMood,
  MarketSummary,
  KBEntity,
  TrackerListing,
  TrackerListResponse,
  TrackerSnapshot,
  TrackerSnapshotResponse,
  TrackerTableRow,
  TrackerMetricValue,
  TrackerHeadlineMetric,
  TrackerGeoEntry,
  TrackerTimeSeriesPoint,
  TrackerEvent,
  TrackerSignal,
  TrackerSourceRef,
} from "./types.js";

export { VERSION } from "./version.js";
